server:
  port: 8081

spring:
  application:
    name: auth-service

  cloud:
    compatibility-verifier:
      enabled: false

  datasource:
    driver-class-name: org.postgresql.Driver
    username: ${DB_USERNAME:postgres}
    password: ${DB_PASSWORD:postgres}
    url: jdbc:postgresql://${POSTGRES_HOST:localhost}:5433/${POSTGRES_DB_PAYMENTS:auth_db}

  jpa:
    hibernate:
      ddl-auto: update # в разработке update, в тесте для liquibase заменить на validate, проде — только ddl-auto: none, всё через Liquibase
    show-sql: true
    properties:
      hibernate:
        format_sql: true

  liquibase:
    enabled: false
    change-log: classpath:db/changelog/db.changelog-master.yaml
    contexts: dev

# FeignClient
delivery-service:
  url: http://localhost:8089

jwt:
  secret: ${JWT_SECRET:PO50Kb9HTXs0CZfgE1c7HpJKFKkYQW6ybn3KDRBM5qO}
  expiration: 86400000 # Время жизни токена в миллисекундах (24 часа)