spring:
  application:
    name: payment-service
  datasource:
    driver-class-name: org.postgresql.Driver
    password: ${POSTGRES_PASSWORD:postgres}
    username: ${POSTGRES_USER:postgres}
    url: jdbc:postgresql://${POSTGRES_HOST:localhost}:5433/${POSTGRES_DB_PAYMENTS:payments}
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true
  liquibase:
    enabled: true
    change-log: classpath:db/changelog/db.changelog-master.yaml
    contexts: test
  threads:
    virtual:
      enabled: true

server:
  port: 8088

#notification-topic: notifications.events