-- 001-create-orders-table.sql
--liquibase formatted sql

--changeset kilianrow:1
CREATE TABLE IF NOT EXISTS orders (
        id bigint not null primary key,
        address varchar(255) not null,
        courier_name varchar(255),
        customer_id bigint,
        eta_minutes integer,
        order_status varchar(255) not null constraint orders_order_status_check check ((order_status)::text = ANY ((ARRAY ['PENDING_PAYMENT'::character varying, 'PAID'::character varying, 'PAYMENT_FAILED'::character varying, 'DELIVERY_ASSIGNED'::character varying, 'DELIVERED'::character varying])::text[])),
        total_amount numeric(19, 2)
);

--changeset kilianrow:2
CREATE TABLE IF NOT EXISTS order_items (
        id bigint not null primary key,
        item_name varchar(255),
        price_at_purchase numeric(38, 2),
        quantity integer,
        order_id bigint constraint fkbioxgbv59vetrxe0ejfubep1w references public.orders
);

--changeset kilianrow:3
CREATE TABLE IF NOT EXISTS items (
        id bigint generated by default as identity primary key,
        name varchar(255) not null,
        price double precision
);