spring:
  application:
    name: delivery-service
  datasource:
    driver-class-name: org.postgresql.Driver
    password: ${POSTGRES_PASSWORD:postgres}
    username: ${POSTGRES_USER:postgres}
    url: jdbc:postgresql://${POSTGRES_HOST:localhost}:5433/${POSTGRES_DB_DELIVERIES:deliveries_db}
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  liquibase:
    enabled: false
    change-log: classpath:db/changelog/db.changelog-master.yaml
    contexts: dev
  kafka:
    consumer:
      group-id: delivery-service-group
      properties:
        spring.json.trusted.packages: "ru.mrkotyaka.commonlibs.*"
    bootstrap-servers: localhost:9092

server:
  port: 8089

order-paid-topic: order.events
delivery-assigned-topic: delivery.events
#notification-topic: notifications.events