spring:
  application:
    name: delivery-service
  datasource:
    driver-class-name: org.postgresql.Driver
    password: ${POSTGRES_PASSWORD:postgres}
    username: ${POSTGRES_USER:postgres}
    url: jdbc:postgresql://${POSTGRES_HOST:localhost}:5433/${POSTGRES_DB_DELIVERIES:deliveries}
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  kafka:
    consumer:
      group-id: delivery-service-group
    bootstrap-servers: localhost:9092
server:
  port: 8089

order-paid-topic: order.events
delivery-assigned-topic: delivery.events