server:
  port: 8091
  error:
    include-message: always
    include-binding-errors: always
    include-stacktrace: never  # на проде лучше never

spring:
  application:
    name: review-service

  cloud:
    compatibility-verifier:
      enabled: false

  datasource:
    driver-class-name: org.postgresql.Driver
    password: ${POSTGRES_PASSWORD:postgres}
    username: ${POSTGRES_USER:postgres}
    url: jdbc:postgresql://${POSTGRES_HOST:localhost}:5433/${POSTGRES_DB_ORDERS:review_db}

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    open-in-view: false

  liquibase:
    enabled: false
    change-log: classpath:db/changelog/db.changelog-master.yaml
    contexts: dev

  kafka:
    consumer:
      group-id: review-service-group
    bootstrap-servers: localhost:9092

# FeignClient
order-service:
  url: http://localhost:8087
delivery-service:
  url: http://localhost:8089

# exchange data topics
review-topic: review.events